// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package qzindustryprinting.proxies;

public class SigningKey extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "qzIndustryPrinting.SigningKey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SigningKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "qzIndustryPrinting.SigningKey"));
	}

	protected SigningKey(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject signingKeyMendixObject)
	{
		super(context, signingKeyMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("qzIndustryPrinting.SigningKey", signingKeyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a qzIndustryPrinting.SigningKey");
	}

	/**
	 * @deprecated Use 'SigningKey.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static qzindustryprinting.proxies.SigningKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return qzindustryprinting.proxies.SigningKey.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static qzindustryprinting.proxies.SigningKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new qzindustryprinting.proxies.SigningKey(context, mendixObject);
	}

	public static qzindustryprinting.proxies.SigningKey load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return qzindustryprinting.proxies.SigningKey.initialize(context, mendixObject);
	}

	public static java.util.List<qzindustryprinting.proxies.SigningKey> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<qzindustryprinting.proxies.SigningKey> result = new java.util.ArrayList<qzindustryprinting.proxies.SigningKey>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//qzIndustryPrinting.SigningKey" + xpathConstraint))
			result.add(qzindustryprinting.proxies.SigningKey.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final qzindustryprinting.proxies.SigningKey that = (qzindustryprinting.proxies.SigningKey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "qzIndustryPrinting.SigningKey";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
