// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package qzindustryprinting.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class SiteCertificate extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "qzIndustryPrinting.SiteCertificate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public SiteCertificate(IContext context)
	{
		this(context, Core.instantiate(context, "qzIndustryPrinting.SiteCertificate"));
	}

	protected SiteCertificate(IContext context, IMendixObject siteCertificateMendixObject)
	{
		super(context, siteCertificateMendixObject);
		if (!Core.isSubClassOf("qzIndustryPrinting.SiteCertificate", siteCertificateMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a qzIndustryPrinting.SiteCertificate");
	}

	/**
	 * @deprecated Use 'SiteCertificate.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static qzindustryprinting.proxies.SiteCertificate initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return qzindustryprinting.proxies.SiteCertificate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static qzindustryprinting.proxies.SiteCertificate initialize(IContext context, IMendixObject mendixObject)
	{
		return new qzindustryprinting.proxies.SiteCertificate(context, mendixObject);
	}

	public static qzindustryprinting.proxies.SiteCertificate load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return qzindustryprinting.proxies.SiteCertificate.initialize(context, mendixObject);
	}

	public static java.util.List<qzindustryprinting.proxies.SiteCertificate> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<qzindustryprinting.proxies.SiteCertificate> result = new java.util.ArrayList<qzindustryprinting.proxies.SiteCertificate>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//qzIndustryPrinting.SiteCertificate" + xpathConstraint))
			result.add(qzindustryprinting.proxies.SiteCertificate.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final qzindustryprinting.proxies.SiteCertificate that = (qzindustryprinting.proxies.SiteCertificate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "qzIndustryPrinting.SiteCertificate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
