// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package qzindustryprinting.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the qzIndustryPrinting module

	public static qzindustryprinting.proxies.Command gET_CommandEntity(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "qzIndustryPrinting.GET_CommandEntity", params);
			return result == null ? null : qzindustryprinting.proxies.Command.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static String gET_SignedMessage(IContext context, qzindustryprinting.proxies.Message _message)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Message", _message == null ? null : _message.getMendixObject());
			return (String)Core.execute(context, "qzIndustryPrinting.GET_SignedMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static qzindustryprinting.proxies.SigningKey gET_SigningKey(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "qzIndustryPrinting.GET_SigningKey", params);
			return result == null ? null : qzindustryprinting.proxies.SigningKey.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static qzindustryprinting.proxies.SiteCertificate gET_SiteCertificate(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "qzIndustryPrinting.GET_SiteCertificate", params);
			return result == null ? null : qzindustryprinting.proxies.SiteCertificate.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static String gET_SiteCertificateString(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (String)Core.execute(context, "qzIndustryPrinting.GET_SiteCertificateString", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static String sUB_CMD_EpsonCut(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (String)Core.execute(context, "qzIndustryPrinting.SUB_CMD_EpsonCut", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static String sUB_CMD_EpsonOpenCashDrawer(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (String)Core.execute(context, "qzIndustryPrinting.SUB_CMD_EpsonOpenCashDrawer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}